services:
  postgres:
    image: postgres
    ports:
      - "5431:5432"
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo-challenge
  
  app:
    build: 
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres:5432/todo-challenge?schema=public"
    ports:
      - "3000:3000"