name: Production - CI

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

    
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Debug docker whoami
        run: docker info && docker whoami

          
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.2.0
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/backend-todo-challenge:latest